# genetics.jl

# This script defines the "alogirthm" used to solve the problem in the form of genes

# Genes are defined in a tree structure, referencing their parents.


###### Example Input ######

# Create All Genes
# Define all Proteins Generated by Genes
# Proteins are all functions
# Note: protein lifetime length is stored in the gene for that protein

println("Genetics Importing Begun")


root 				=	Gene("", 1.0, "noProtein", 0.0)

	function noProtein() 
		println("Never used this function, baka")
	end




destroyMoleculeGene =	Gene("root", 0.5, "destroyMolecule", 5.0)

	function destroyMolecule()
		println("Running destroyMolecule")
	end


# Finally set list of genes/proteins and their initial abundances
pa1 = ProteinAbundance("root", 0.0)
pa2 = ProteinAbundance("destroyMoleculeGene", 0.0)
proteinDistribution = [pa1, pa2]


println("Genetics Importing Finished")