# genetics.jl

# This script defines the "alogirthm" used to solve the problem in the form of genes

# Genes are defined in a tree structure, referencing their parents.


###### Example Input ######

# Create All Genes
# Define all Proteins Generated by Genes
# Proteins are all functions
# Note: protein lifetime length is stored in the gene for that protein

println("Genetics Importing Begun")


function root_protein(molecule) 
	#println("Never used this function, baka")
	return [molecule]
end

root = Gene(nothing, root_protein, 1.0,  0.0)

function dmg_protein(molecule)
	#println("Running destroyMolecule")
	return []
end

destroyMoleculeGene = Gene(root, dmg_protein, 0.5, 5.0)


# Finally set list of genes/proteins and their initial abundances
pa1 = ProteinAbundance(root_protein, 22)
pa2 = ProteinAbundance(dmg_protein, 33)
proteinDistribution = [pa1, pa2]


println("Genetics Importing Finished")